//Lucas Gabriel Costa
import javax.swing.JOptionPane;

public class MenuRh extends javax.swing.JFrame {

    Banco bd = Banco.getInstance();
    public static MenuRh menuRh;
    
    public static MenuRh getMenuRh() {
        if(menuRh == null) {
            menuRh = new MenuRh();
        }
        menuRh.setVisible(true);
        menuRh.setLocationRelativeTo(null);
        return menuRh;
    }
    private MenuRh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoEsq1 = new javax.swing.JPanel();
        lblMenu1 = new javax.swing.JLabel();
        lblRH1 = new javax.swing.JLabel();
        btCadFunc = new javax.swing.JButton();
        btConsFunc = new javax.swing.JButton();
        btAltFunc = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuTools = new javax.swing.JMenu();
        menuRelatorios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        fundoEsq1.setBackground(new java.awt.Color(153, 153, 153));

        lblMenu1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMenu1.setText("Menu");

        lblRH1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblRH1.setText("RH");

        btCadFunc.setText("Cadastrar Funcionário");
        btCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadFuncActionPerformed(evt);
            }
        });

        btConsFunc.setText("Consultar Funcionário");
        btConsFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsFuncActionPerformed(evt);
            }
        });

        btAltFunc.setText("Alterar Funcionário");
        btAltFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundoEsq1Layout = new javax.swing.GroupLayout(fundoEsq1);
        fundoEsq1.setLayout(fundoEsq1Layout);
        fundoEsq1Layout.setHorizontalGroup(
            fundoEsq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoEsq1Layout.createSequentialGroup()
                .addGroup(fundoEsq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fundoEsq1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btCadFunc))
                    .addGroup(fundoEsq1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btConsFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fundoEsq1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btAltFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fundoEsq1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(fundoEsq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundoEsq1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblRH1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fundoEsq1Layout.setVerticalGroup(
            fundoEsq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoEsq1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblMenu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRH1)
                .addGap(37, 37, 37)
                .addComponent(btCadFunc)
                .addGap(18, 18, 18)
                .addComponent(btConsFunc)
                .addGap(18, 18, 18)
                .addComponent(btAltFunc)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        menuTools.setText("Tools");

        menuRelatorios.setText("Relatórios..");

        jMenuItem1.setText("Relatório Funcionários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuRelatorios.add(jMenuItem1);

        menuTools.add(menuRelatorios);

        menuBar.add(menuTools);

        menuExit.setText("Exit");
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExitMouseClicked(evt);
            }
        });
        menuBar.add(menuExit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fundoEsq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoEsq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadFuncActionPerformed
        this.dispose();
        CadFunc.getCadFunc();
    }//GEN-LAST:event_btCadFuncActionPerformed

    private void btConsFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsFuncActionPerformed
        Funcionario func = getFunc();
        if(func != null) {
            if(func instanceof Assalariado) {
                dispose();
                CadFuncAssalariado.getCadFuncAssalariado().consFunc((Assalariado) func);
            }
            else if(func instanceof Comissionado) {
                dispose();
                CadFuncComissionado.getCadFuncComissionado().consFunc((Comissionado) func);
            }
            else if(func instanceof Horista) {
                dispose();
                CadFuncHorista.getCadFuncHorista().consFunc((Horista) func);
            }
        }
    }//GEN-LAST:event_btConsFuncActionPerformed
    public Funcionario getFunc() {
        Funcionario func = (Funcionario) new Assalariado();
        try {
            func.setCpf(JOptionPane.showInputDialog(null, "Informe CPF para busca", "Consulta Funcionário", JOptionPane.PLAIN_MESSAGE));
        }
        catch(MyException mye) {
        }
        catch(NullPointerException npe) {
        }
        return bd.consFunc(func);
    }
    private void btAltFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltFuncActionPerformed

        Funcionario func = getFunc();
        if(func != null) {
            if(func instanceof Assalariado) {
                CadFuncAssalariado.getCadFuncAssalariado().altFunc((Assalariado) func);
            }
            else if(func instanceof Comissionado) {
                CadFuncComissionado.getCadFuncComissionado().altFunc((Comissionado) func);
            }
            else if(func instanceof Horista) {
                CadFuncHorista.getCadFuncHorista().altFunc((Horista) func);
            }
        }
    }//GEN-LAST:event_btAltFuncActionPerformed

    private void menuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseClicked
        this.dispose();
        Principal.getPrincipal();
    }//GEN-LAST:event_menuExitMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.getPrincipal();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        RelatFuncs.getRelatFuncs();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltFunc;
    private javax.swing.JButton btCadFunc;
    private javax.swing.JButton btConsFunc;
    private javax.swing.JPanel fundoEsq1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblMenu1;
    private javax.swing.JLabel lblRH1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuTools;
    // End of variables declaration//GEN-END:variables
}
